# Add 'frontend' label to any change to *.js files as long as the `main.js` hasn't changed
frontend:
  - any: ['src/**/*.js', '!src/main.js']

# Add 'backend' label to any change to *.py files
backend:
  - '**/*.py'

# Add 'documentation' label to any change to *.md files
documentation:
  - '**/*.md'

# Add 'css' label to any change to *.css files
css:
  - '**/*.css'

# Add 'astro' label to any change to *.astro files
astro:
  - '**/*.astro'
