name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Vitest tests
        run: npm test

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test:e2e

      #      - name: Run tests
      #        run: npx playwright test # might be doubling up

      - name: Deploy to Cloudflare Pages
        if: success() && github.ref == 'refs/heads/main' # Only deploy on main branch
        uses: cloudflare/pages-action@1.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: dot-com
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
